apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: myjavaapp
  version: 2.7.1
spec:
  type: Nodeport
  ports:
   - port: 8080
     nodeport: 30001
     protocal: TCP
  selector:
    app: myjavaapp
    version: 2.7.1